version: 0.3.0
image: Visual Studio 2022
#install:
#- cmd: choco install Pester
build_script:
  - ps: ./build.ps1
test:
  assemblies:
    only:
    - 'bin\test\*.Tests.dll'
#after_test:
#- ps: $res = Invoke-Pester -Path "." -OutputFormat NUnitXml -OutputFile TestsResults.xml -PassThru
#- ps: (New-Object 'System.Net.WebClient').UploadFile("https://ci.appveyor.com/api/testresults/nunit/$($env:APPVEYOR_JOB_ID)", (Resolve-Path .\TestsResults.xml))
#- ps: if ($res.FailedCount -gt 0) { throw "$($res.FailedCount) tests failed."}
