// Auto-Generated by FAKE; do not edit
// <auto-generated/>
using System.Reflection;

[assembly: AssemblyTitle("NGettext-Avalonia")]
[assembly: AssemblyVersion("0.0.1")]
[assembly: AssemblyInformationalVersion("0.0.1")]
[assembly: AssemblyProduct("NGettext-Avalonia")]
[assembly: AssemblyCompany("(For free use)")]
[assembly: AssemblyCopyright("© Robert J. Engdahl")]
[assembly: AssemblyFileVersion("0.0.1")]
[assembly: AssemblyDescription("Proper internationalization support for Avalonia via NGettext")]
namespace System {
    internal static class AssemblyVersionInformation {
        internal const System.String AssemblyTitle = "NGettext-Avalonia";
        internal const System.String AssemblyVersion = "0.0.1";
        internal const System.String AssemblyInformationalVersion = "0.0.1";
        internal const System.String AssemblyProduct = "NGettext-Avalonia";
        internal const System.String AssemblyCompany = "(For free use)";
        internal const System.String AssemblyCopyright = "© Robert J. Engdahl";
        internal const System.String AssemblyFileVersion = "0.0.1";
        internal const System.String AssemblyDescription = "Proper internationalization support for Avalonia via NGettext";
    }
}
